#!/bin/bash

if [[ -d ~/rpmbuild ]]; then
 rm -rf ~/rpmbuild
fi

sudo yum -y install rpmdevtools && rpmdev-setuptree

if [[ -z "$1" ]]; then
  read -p "Version: " version
else
  version=$1
fi

git clone https://github.com/dpeterka/rpm-etcd.git rpm-etcd

cp rpm-etcd/master/etcd.spec ~/rpmbuild/SPECS/etcd.spec
sed "s/VERSION/${version}/" ~/rpmbuild/SPECS/etcd.spec
wget https://github.com/coreos/etcd/releases/download/v${version}/etcd-v${version}-linux-amd64.tar.gz -O ~/rpmbuild/SOURCES/etcd-v${version}-linux-amd64.tar.gz
cp rpm-etcd/etcd.initd ~/rpmbuild/SOURCES/etcd.initd
cp rpm-etcd/etcd.sysconfig ~/rpmbuild/SOURCES/etcd.sysconfig
cp rpm-etcd/etcd.nofiles.conf ~/rpmbuild/SOURCES/etcd.nofiles.conf
cp rpm-etcd/etcd.logrotate ~/rpmbuild/SOURCES/etcd.logrotate
rpmbuild -bb ~/rpmbuild/SPECS/etcd.spec